model:
  nr_heads: 4
  nr_mamba_layers: 1
  dim: 768
  input_dims:
  - 512
  - 1024
  - 1280
  - 1536
  l_dim: 256
  att_dim: 256
  dropout: 0.2
  d_state: 128
  model_name: cobraII
ssl:
  moco_m: 0.99
  moco_t: 0.2
  optimizer: adamw
  lr: 5e-4
  warmup_epochs: 50
  weight_decay: 0.1
  momentum: 0.9
  epochs: 2000
  workers: 56
  batch_size: 1024
general:
  nr_feats: 768
  fms:
  - mahmood-conch
  - mahmood-uni
  - virchow2
  - bioptimus
  feat_base_paths:
  - tcga-5x
  - tcga-10x
  - tcga-20x
  - tcga-30x
  paths:
    out_dir: /path/to/cobra/model/cobraII

