model:
  nr_heads: 8
  nr_mamba_layers: 3
  dim: 768
  input_dim: 1536
  l_dim: 256
  att_dim: 128
  dropout: 0.25
  d_state: 128
  model_name: cobraII
ssl:
  moco_m: 0.99
  moco_t: 0.2
  optimizer: adamw
  lr: 1e-5
  warmup_epochs: 50
  weight_decay: 0.1
  momentum: 0.9
  epochs: 2000
  workers: 56
  batch_size: 2048
general:
  nr_feats: 1024
  fms:
  - dinoSSL
  - mahmood-conch
  - mahmood-uni
  - virchow2
  - h_optimus_0
  feat_base_paths:
  # - /data/horse/ws/s1787956-TCGA/features/features-1x
  # - /data/horse/ws/s1787956-TCGA/features/features-2x
  - /data/horse/ws/s1787956-TCGA/features/features-5x
  - /data/horse/ws/s1787956-TCGA/features/features-10x
  - /data/horse/ws/s1787956-TCGA/features/features-20x
  - /data/horse/ws/s1787956-TCGA/features/features-30x
  paths:
    out_dir: /data/cat/ws/s1787956-cobra/outs
