model:
  nr_heads: 8
  nr_mamba_layers: 2
  dim: 768
  input_dims:
  - 768
  - 1024
  - 1280
  - 1536
  l_dim: 256
  att_dim: 96
  dropout: 0.25
  d_state: 128
  model_name: cobra

ssl:
  moco_m: 0.99
  moco_t: 0.2
  optimizer: adamw
  lr: 5e-4
  warmup_epochs: 50
  weight_decay: 0.1
  momentum: 0.9
  epochs: 2000
  workers: 32
  batch_size: 1024
    
general:
  nr_feats: 1024
  fms:
    - ctranspath
    - uni
    - virchow2-class
    - bioptimus
  feat_base_paths: 
    - 5x-features
    - 9x-features
    - 20x-features
  feat_cohorts:
    - tcga_brca
    - tcga_lung
    - tcga_crc
    - tcga_stad
  paths:
    out_dir: /path/to/cobra/model/cobra

