train:
  csv_path: /p/scratch/mfmpm/tim/data/Engelmann/metadata/clini_table_ed.xlsx
  target_column: Klassifikation
  patient_id_column: PATIENT
  h5_path: /p/scratch/mfmpm/tim/data/Engelmann/processed_data/hybrid_cobra-224-256/cobraII_hybrid_conch_v2_feats.h5
  output_folder: /p/scratch/mfmpm/tim/data/Engelmann/crossval-cobra-hybrid-conch-v2-224-256
  hps:
    lr: 0.0005
    hidden_dim: 512
    max_epochs: 64
    patience: 16
    batch_size: 16
    num_workers: 8
    n_folds: 5
    dropout: 0.3

deploy:
  csv_path: /mnt/bulk-neptune/timlenz/stamp/metadata/cptac_brca.csv
  target_column: PGR
  patient_id_column: PATIENT
  h5_path: /mnt/bulk-neptune/timlenz/COBRA/outputs-fe-64/cobraII/CPTAC-BRCA/cobraII_feats_BRCA.h5
  output_folder: /mnt/bulk-neptune/timlenz/COBRA/outputs/cobraII-BRCA-PGR-64
  label_encoder_path: /mnt/bulk-neptune/timlenz/COBRA/outputs/cobraII-BRCA-PGR-64/label_encoder.pkl
  hps:
    hidden_dim: 256
    n_folds: 5